spring.application.name=nutriVision


spring.datasource.url=jdbc:mysql://localhost:3306/nutrivision_db
spring.datasource.username=root
spring.datasource.password=21111979

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true